### ISSUE TITLE
Request to add helm interface to list all the gulp tasks 

### ISSUE THREAD

**Issue by zilongshanren** [stevenremot/emacs-gulpjs#1]

**Comment by stevenremot** [comment]
Hey, that would be really cool! I will add it when I have some time to spend on it, maybe next week.

**Comment by zilongshanren** [comment]
@stevenremot 
`gulp -T or --tasks will display the task dependency tree for the loaded gulpfile` could list all the tasks.
:+1:  Thanks, this package really helpful. I need to run gulp tasks 100+ times a day :smile:

**Comment by zilongshanren** [comment]
@stevenremot 
I have implemented a simple one at https://github.com/stevenremot/emacs-gulpjs/pull/2
please check it out.
